### ISSUE TITLE
Installation section

### ISSUE THREAD

**Issue by lfarah** [dabing1022/DBMetaballLoading#1]
Hey @dabing1022, I'd be cool to add an **Installation Section** on the `Readme.md`
You can take a look at my [iOS Readme Template](https://github.com/awesome-labs/iOS-readme-template) to see how you can do it.

**Comment by dabing1022** [comment]
Hi, @lfarah , I updated README after supporting CocoaPods. Thanks for your link. :]

**Comment by lfarah** [comment]
You're welcome 😉
