### ISSUE TITLE
Organize files

### ISSUE THREAD

**Issue by lfarah** [dabing1022/DBMetaballLoading#4]
We could create a `/Source` folder with [those files](https://github.com/dabing1022/DBMetaballLoading/tree/master/DBMetaballLoading/Source) inside, so the **Library** is in another place as the **Example App**
Check [this library](https://github.com/hyperoslo/Cache) as an example.

What are your thoughts? 🤔

**Comment by dabing1022** [comment]
It seems like a good idea.
