### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [dabing1022/DBMetaballLoading#6]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by dabing1022** [comment]
@lfarah Hi, I'm very glad now we can rock Swift3 in our project.  

See b4d1e94273069b141d499d8778f4b6f12ccecbb9. If there is any problem, please let me know.

Cheers:]

**Comment by lfarah** [comment]
Thank you so much, @dabing1022! 🎉 🎉 🎉 🎉
